
= KCEO Glossary of Terms and Definitions

== Introduction

The KCEO Glossary of Terms and Definitions is a comprehensive resource
that serves as an invaluable reference guide for seeking clarity and a
deeper understanding of the field of Earth observation. This extensive
compilation brings together a wide range of terms, concepts, and
definitions that are directly relevant to Earth observation,
encompassing various disciplines such as remote sensing, satellite
imagery, geospatial analysis, climate adaptation, and more. By acting as
a reliable compass, this glossary helps to navigate the intricate and
specialized terminology associated with Earth observation, ensuring
effective communication and knowledge sharing.

As a living document, the KCEO Glossary of Terms and Definitions is in a
constant state of evolution and is continuously adapted to incorporate
emerging concepts. This ensures that it remains up-to-date.

The KCEO Glossary of Terms and Definitions is serves as an indispensable
tool to cater our needs, promote effective communication, and stay
abreast of the ever-evolving landscape of Earth observation.

[[start]]
[reviewer="Lahsaini",date=20240420,from=start,to=end]
**** 
Modify the introduction

****
[[end]]

== General terms

=== Ancillary data 

Ancillary data:: Data acquired on-board but not obtained from the main instrument
itself (usually provided as part of Level 0 data). They have the primary
purpose to serve the processing of main instrument data (e.g. orbit
position and velocity of platform).

{empty}[Source: ESA/CEOS?, modified]

Alternative:

Ancillary data:: Data other than instrument measurements, originating in the instrument
itself or from the satellite, required to perform processing of the
data. They include orbit data, attitude data, time information,
spacecraft engineering data, calibration data, data quality information,
and data from other instruments or earth system models.

{empty}[Source CEOS-ARD PFS template 20220302]

_Data_ acquired in context of an _observation_ required to perform
processing

=== Auxiliary data

_Data_ which enhance processing and utilization of main instrument data.
The auxiliary data are usually not captured by the same data collection
process as the main instrument data. Auxiliary data include data
collected by any other platform or process. Examples are e.g.
meteorological data received from ECWMF/Met. Offices. Auxiliary data
help in data processing, but are also data sets in their own right**.**

{empty}[Source: ESA/CEOS?, modified]

Alternative:

The data required for instrument processing, which does not originate in
the instrument itself or from the satellite. Some auxiliary data will be
generated in the ground segment, whilst other data will be provided from
external sources.

{empty}[Source CEOS-ARD PFS template 20220302]

=== Cell

Spatial, spatio-temporal zone or temporal unit of geometry with
dimensionality greater than 0, associated with a zone

NOTE1: All cells within a DGGS share the dimensionality of the DGGS's
parent global geometry. DGGSs with dimensionality of 0 are not
supported.

NOTE 2: Cells are the unit of geometry in a DGGS, and the geometry of
the region of space-time occupied by a zone is a cell.

NOTE 3: While the terms cell and zone are often used interchangeably,
"zone" is the strictly preferred term. Cell is entirely appropriate when
specifically discussing a zone's geometry or topology.

{empty}[SOURCE: ISO 19170:2021]

=== Duration

non-negative interval quantity of time equal to the difference between
the final and initial instants of a time

NOTE 1: The duration is one of the base quantities in the International
System of Quantities (ISQ) on which the International System of Units
(SI) is based. The term “time” instead of “duration” is often used in
this context and also for an infinitesimal duration.

NOTE 2: For the term “duration”, expressions such as “time” or “time
interval” are often used, but the term “time” is not recommended in this
sense and the term “time interval” is deprecated in this sense to avoid
confusion with the concept of “time interval”.

NOTE 3: The exact duration of a time scale unit depends on the time
scale used. For example, the durations of a year, month, week, day, hour
or minute, may depend on when they occur [in a Gregorian calendar, a
calendar month can have a duration of 28, 29, 30, or 31 days; in a
24-hour clock, a clock minute can have a duration of 59, 60, or 61
seconds, etc.]. Therefore, the exact duration can only be evaluated if
the exact duration of each is known.

NOTE 4: This definition is closely related to NOTE 1 of the
terminological entry “duration” in IEC 60050-113:2011, 113–01–13.

{empty}[SOURCE: ISO 8601-1:2019, 3.1.1.8]

[#_Toc161308962 .anchor]####Earth observation

Is a science domain dealing with technologies and methods of collecting
and analysing _observations_ about the different spheres (Geosphere,
Atmosphere, Hydrosphere, Cryosphere, Biosphere, Anthroposphere) of our
planet. This includes _remote-sensing_, such as satellite imagery, as
well as in-situ observations, e.g., with ground-based devices.

NOTE 1: Earth Observation (EO) can be categorised by location of the
sensor into space-borne, air-borne, sea-borne, ground-based, underwater
and underground EO.

{empty}[Source: modified GEO definition
https://earthobservations.org/geo_wwd.php]

[#_Toc161308963 .anchor]####Earth Observation product

A representation of a phenomenon that can be coded into information. A
product serves multiple purposes and cross-domain applications. A
characteristic of EO products is that they should undergo some data
transformation for being considered decision-ready or inference-ready
information.

NOTE 1: aka geophysical and biophysical parameters (surface temperature,
leaf area index, etc.)

{empty}[SOURCE: KCEO]

[#_Toc161308964 .anchor]####Earth Observation based output

Any data or information derived from EO products. It may be generated
for addressing specific use cases or user needs. It is the result of any
type of data processing (classification, rearranging, sorting,
aggregating, mathematical computation, filtering) and/or data
integration (fusion, data assimilation) with other EO products and/or
geospatial data that changes the property of the original EO product. It
is the result of a non-invertible operation so that the original EO
product can’t be recovered.

{empty}[SOURCE: KCEO]

[#_Toc161308965 .anchor]####Entity

Something that has separate and distinct existence and objective or
conceptual reality

{empty}[SOURCE: https://www.iso.org/standard/59221.html[ISO 19119:2016],
4.1.6]

=== Geographic data 

data with implicit or explicit reference to a location relative to the
Earth

NOTE 1: _Geographic_ _information_ is also used as a term for
information concerning phenomena implicitly or explicitly associated
with a location relative to the Earth.

{empty}[SOURCE: https://www.iso.org/standard/59193.html[ISO 19109:2015],
4.13; ISO 19109:2005]

=== 

=== Geographic identifier

Spatial reference in the form of a label or code that identifies a
location.

EXAMPLE: “Spain” is an example of a label (country name); “SW1- 3AD” is
an example of a code (postcode).

{empty}[SOURCE: ISO 19112:2019, 3.1.2]

=== Geospatial data/information

Consisting of, derived from, or relating to _data_ that is directly
linked to specific geographical locations

[Source: https://www.merriam-webster.com/dictionary/geospatial ,

https://isotc211.geolexica.org/concepts/202/, accessed 20221010]

=== Grid

network composed of two or more sets of curves in which the members of
each set intersect the members of the other sets in an algorithmic way

NOTE 1: The curves partition a space into grid cells

{empty}[SOURCE: ISO 19123:2005, 4.1.23]

=== Information

The result of organisation, interpretation, categorisation,
classification, or some other form of processing of _data_ attaching to
it a certain meaning that can be understood by the addressee.

NOTE 1: Information depends on _data_ and is targeted.

{empty}[SOURCE: gEOGlos]

=== In-situ observation

‘In-situ’ describes _observations_ performed in the same place where a
phenomenon occurs, normally without isolating it from other systems (its
environment) or altering its pre-observation state. The main
characteristic of such observations is that distance has no or only
negligible (within _uncertainty_) influence on the _value_ of the
_property_ observed. In-situ _observations_ therefore often require
either direct physical contact or small distances between a _sensor_ and
the observed phenomenon.

NOTE 1: _Observations_ not fulfilling these conditions are considered
_Remote Sensing_.

{empty}[Source: own (Peter)]

=== Laboratory observation

Laboratory _observations_ are (usually) in-situ observations in which
the object or phenomenon is isolated from other systems or altered in
its ‘original’ conditions or environment.

Note:

=== Location

Particular _place_ referenced by an _identifier_

NOTE 1 to entry: While a (geo)location identifies a geographic place, it
may also be associated with objects other than the Earth +
NOTE 2 to entry: While location in principle covers 0- to 3-dimensional
spatial geometries, it should not be used for 0- and 1-dimensional
geometries (_positions_ and paths)

EXAMPLE "Madrid", "California".

{empty}[SOURCE: https://www.iso.org/standard/70742.html[ISO 19112:2019],
(E), 3.1.3, modified, note 2 added]

=== Measurement

A measurement is an _observation_ of a _quantity_.

NOTE 1: The process of collecting a measurement is called *measuring*.

{empty}[Source: gEOGlos (VIM ?, modified)]

=== Period

Particular era or span of time

NOTE 1: Periods are intervals named with a period identifier

{empty}[SOURCE: ISO 19170:2021]

=== Period identifier

Temporal reference in the for of a label or code that identifies a
period

NOTE 1: period identifiers are the temporal equivalent of geographic
identifiers as specified in ISO 19912

{empty}[SOURCE: ISO 19170:2021]

=== Quantity

A _property_ whose instances can be compared by ratio or only by order

{empty}[Source: gEOGlos(VIM4 Notes omitted)]

=== Remote Sensing (or Remote Observation)

Remote sensing is a type of _observation_ performed at a significant
distance from a _phenomenon_. ‘Significant’ in this context means that
the distance has, or may have, a non-negligible impact on the _value_ of
the _property_ observed. The effect of the distance on the acquired
_data_ is the main distinction criteria between ‘remote’ and ‘in-situ’
observations.

NOTE 1: the opposite of ‘_remote_’ is ‘_in-situ'_

{empty}[Source: own (Peter)]

=== Representativity

*[…]*

NOTE 1: WIGOS metadata standard defines representativeness as the extent
of the region around the observation of which it is representative

[#_Toc161308980 .anchor]####Service provider

An institutional body, an organisation or programme that provides
reliable, trusted (authoritative?) EO information and that has the
financial resources to sustain the provision.

=== 

=== Uncertainty

Non-negative parameter, associated with data, which characterizes the
dispersion of the values that could reasonably be attributed to the
feature or phenomenon. In case of quantitative data, the uncertainty may
be, for example, a standard deviation (or a given multiple of it), or
the half-width of an interval having a stated level of confidence. For
qualitative data uncertainty may be, for example, expressed by
commission, omission and overall errors.

NOTE 1: in natural or ordinary language the term accuracy is often used
to express qualitatively the uncertainty associated with data, such as
‘the data from this thermometer is very accurate vs not very accurate’.
This usage of the term ‘accuracy’, whilst it may be common in
conversational context should be abandoned in technical discussions in
favour of ‘uncertainty’ which does not require the knowledge of the
‘real’ value.

=== User

In the context of the KCEO, an entity (person, organization,
institution, etc.) that is requesting data or information with certain
characteristics described by needs and/or requirements.

{empty}[SOURCE: KCEO]

=== 

=== Validation

process of assessing, by independent means, the quality of the data
products derived from the system outputs

Note 1 to entry: In this part of ISO 19159, the term validation is used
in a limited sense and only relates to the validation of calibration
data in order to control their change over time.

{empty}[SOURCE:ISO/TS 19101‑2:2008, 4.41]

Alternative:

Validation aims to verify that the specified requirements are achieved
or compliant. This involves comparing mission products with
representative reference data, considering various observation
conditions, ensuring the quality and traceability of the reference data
used.

{empty}[SOURCE: BIPM; QA4EO; ESA ?, modified]

Alternative:

The assurance that a product, service, or system meets the needs of the
customer and other identified stakeholders. It often involves acceptance
and suitability with external customers.

{empty}[SOURCE: EU-US Land Imaging EO Collaboration]

=== Verification

provision of objective evidence that a given item fulfils specified
requirements.

Note 1 to entry: When applicable,measurement uncertainty should be taken
into consideration.

Note 2 to entry: The item may be, e.g. a process, measurement procedure,
material, compound, or measuring system.

Note 3 to entry: The specified requirements may be, e.g. that a
manufacturer's specifications are met.

Note 4 to entry: Verification should not be confused with calibration.
Not every verification is a validation.

{empty}[SOURCE:ISO/IEC Guide 99:2007, 2.44]

Alternative:

The evaluation of whether or not a product, service or system complies
with a regulation requirement, specification, or imposed condition. It
often an internal process.

{empty}[SOURCE: EU-US Land Imaging EO Collaboration]

Alternative:

Verification serves as a means to evaluate the reliability of the data
in the absence of a reference dataset, allowing for an assessment of its
standalone performance. It involves confirming the consistency and
internal coherence of the data without direct comparison to external
reference sources. c

{empty}[SOURCE: KCEO]

== EO Product attributes

[#_Toc161308986 .anchor]##[.underline]#Area of interest#

It is the zone in 2D or 3D for which the information or data is
requested. It can be discontinuous in space, in other words it can
consist in the union of many separate zones (e.g., Natural Reserves in
Africa, Urban environments, etc.).

The attribute indicates a request for spatially complete data within the
AOI zone(s).

[width="100%",cols="34%,34%,32%",options="header",]
|===
|Type |Entry format example |Valid units
|Geographical/administrative identifier |NUTS3, LAU, Natura 2000 site
|unitless
|===

{empty}[SOURCE: KCEO]

=== 

=== [.underline]#Band central wavelength#

A single wavelength value within the sensitivity interval of a
spectroradiometric sensor which represents the respective band. It could
be either the mean, the median, the maximum sensitivity, or any other
reasonable value chosen to be representative.

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|0.545 *μm* |micrometre (*μm*), millimetre (mm), centimetre (cm)
|===

=== Confidence interval 

The probability that the quantity lies in the interval, conditioned on
the measuring or modelling assumptions.

{empty}[SOURCE: KCEO]

=== Coverage interval

Interval containing the set of
https://jcgm.bipm.org/vim/en/2.11.html[true quantity values] of a
https://jcgm.bipm.org/vim/en/2.3.html[measurand] with a stated
probability, based on the information available

{empty}[SOURCE: BIPM-VIM]

[#_Toc161308990 .anchor]##[.underline]#Latency#

It is the period between the end of sensing of a phenomenon to the
beginning of availability of a specific product.

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|1 s, 2 h, |second, hour, day, month, year
|===

NOTE 1: CEOS Wiki describes latency as “the time delay introduced by
automated data +
processing or network transmission between the occurrence of an event
and the use of the processed data.”

{empty}[SOURCE: KCEO]

=== [.underline]#Location error#

Indicate the agreement between the represented location of an object and
the true location.

{empty}[SOURCE: KCEO]

=== [.underline]#Measurement uncertainty#

Uncertainty associated with the method of measurement.

{empty}[SOURCE: CEOS Wiki adopted from JCGM GUM]

=== [.underline]#Minimum Mapping Unit# 

The area of the smallest feature that is still represented on a map

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|1 ha |Square meter (*m^2^*), hectar (ha)
|===

{empty}[SOURCE: CGLS]

=== Minimum Mapping Width

The width of the smallest linear feature that is still represented on a
map

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|20 m |Meter (m)
|===

{empty}[SOURCE: CGLS]

[#_Toc161308995 .anchor]##[.underline]#Quality indicator#

A quality indicator shall provide sufficient information to allow all
users to readily evaluate +
the “fitness for purpose” of the data or derived product. A Quality
Indicator may be a number, +
set of numbers, graph, uncertainty budget, or a simple “flag”.

{empty}[SOURCE: CEOS Wiki]

[#_Toc161308996 .anchor]##[.underline]#Spatial completeness#

The presence or absence of gaps, which are missing values in an
otherwise continuous spatial data series. For example, surface soil
moisture retrieved from microwave satellite sensors may present gaps in
mountainous terrains.

{empty}[SOURCE: KCEO]

=== [.underline]#Spatial consistency#

It indicates that the spatial statistical properties of the data depend
only on the underlaying physical processes and don’t depend on other
factors such as fusing different products or sensors. Also, the validity
of the assumptions of the procedure to produce information holds true
across the whole spatial range.

{empty}[SOURCE: KCEO]

=== [.underline]#Spatial extent#

The _zone_ or region of space described by a _geographic identifier_ in
the form of a label or code, or by a bounding box. It consists in the
maximum extent (the spatial boundary or limits) within which the user is
requesting data.

The attribute represents the maximum spatial extent of the AOI, and in
case the AOI is made of many discontinuous zones then it represents the
maximum extent of the union of all the zones.

For example, if a user is requesting information about degradation of
African protected sites, then the AOIs are the protected sites, and the
spatial extent is the African continent.

NOTE 1: WIGOS metadata standard defines it as the typical spatial
georeferenced volume covered by the observations

{empty}[SOURCE: Adapted from ISO 19170-1:2021]

=== [.underline]#Spatial reporting unit#

The smallest spatial object of interest that may be used for reporting
and for which the information should be aggregated.

[width="100%",cols="34%,34%,32%",options="header",]
|===
|Type |Entry format example |Valid units
|Geographical/administrative identifier |Africa, NUTS3, LAU, Natura 2000
site |unitless

|Grid [x, y] |2 x 2 meter, 0.1 x 0.2 degrees ; |Meter, degrees
|===

NOTE 1: WIGOS 2019 use ‘spatial reporting interval’ probably assuming
the observations are reported on a grid with regular spacing/intervals.

{empty}[SOURCE: KCEO]

[#_Toc161309000 .anchor]##[.underline]#Spatial resolution#

It is the spatial sampling scheme that determines the smallest object
that can be identified or resolved in a gridded spatial discretization.

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|2 x 2 m; 0.1 x 0.4 degrees |Meter, degrees
|===

NOTE 1: Also called _grid spacing_

{empty}[SOURCE:]

=== [.underline]#Spectral# [.underline]#resolution# 

Measure of the ability to resolve features in the electromagnetic
spectrum.

{empty}[SOURCE: KCEO]

=== [.underline]#Spectral band#

Part of the electromagnetic spectrum of specific wavelengths. In remote
sensing usually described by central wavelength and bandwidth.

=== [.underline]#Spectral Bandwidth#

the range of the spectral band

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|0.429-0.457 *μm* |micrometre (*μm*), millimetre (mm), centimetre (cm)
|===

[#_Toc161309004 .anchor]##[.underline]#Stability#

It refers to the maximum acceptable change in uncertainty per decade.

NOTE 1: GCOS uses bias or systematic errors instead of uncertainty

{empty}[SOURCE: modified from GCOS 2022]

[#_Toc161309005 .anchor]##[.underline]#Temporal consistency#

It indicates that the temporal statistical properties of the sample
depend only on the underlaying physical processes and don’t depend on
other factors such as fusing different products or sensors.

{empty}[SOURCE: KCEO]

=== [.underline]#Temporal extent#

The period during which data was collected, observations were made, or
model was run.

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|Y/m/d - Y/m/d |Not Applicable
|===

NOTE 1: In W3C is the definition of temporal coverage

NOTE 2: Time period covered by a series of observations inclusive of the
specified date/time indications (measurement history). Defined based on
the beginning and end dates of observations. WIGOS Metadata]

{empty}[SOURCE: adapted from W3C]

=== [.underline]#Temporal reporting period# 

The time period used for reporting and for which the information should
be aggregated from the native temporal resolution.

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|1 s, 2 h, 1 d |second, hour, day, month, year
|===

{empty}[SOURCE: modified WIGOS Metadata Standard 2019]

=== [.underline]#Temporal# [.underline]#resolution# 

The observation or model output representing regular intervals and
specifying the length of the interval that determines the smallest event
or process that can be resolved. (e.g., the period between observations,
the time steps in a model).

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|1 s, 2 h, 1 m |second, hour, day, month, year
|===

NOTE 1: WIGOS 2019 distinguishes between _sampling time period_, as the
period over which a measurement is taken, and _temporal sampling
interval_ as the time period between the beginning of consecutive
sampling periods. Temporal resolution in this Glossary is equivalent to
sampling time period as used by WIGOS.

{empty}[SOURCE: KCEO]

=== [.underline]#Temporal revisit#

The interval between successive observations

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|1 s, 2 h |second, hour, day, month, year
|===

NOTE 1: In remote sensing it is also called repeat cycle

NOTE 2: More generally it is known as *temporal sampling interval*

{empty}[SOURCE: KCEO]

=== Time of year

the time of the year that the variable is observed or simulated by a
model

[width="100%",cols="25%,25%,50%",options="header",]
|===
|type |Entry format example |Valid unit
|timestamp |m/d |Not Applicable
|timerange |m/d - m/d |Not Applicable
|===

{empty}[SOURCE: KCEO]

=== [.underline]#Time of day#

the time of the day that the variable or parameter is observed or
simulated by a model

[width="100%",cols="25%,25%,50%",options="header",]
|===
|type |Entry format example |Valid unit
|timestamp |18:00 h (0-24) |Hours
|timerange |18:00 – 20:00 h |Hours
|===

NOTE 1: In remote sensing it is also known as time of overpass

{empty}[SOURCE: KCEO]

[#_Toc161309012 .anchor]####Timeliness

It is the period between the moment of requesting information to the
moment of availability of information.

* Near Real-Time (NRT): delivered less than 3 hours after requesting
information
* Slow-Time Critical (STC): delivered within 48 hours after requesting
information
* Non-Time Critical (NTC): typically delivered within 1 month after
requesting information

NOTE 1: In some context also known as delivery time.

NOTE 2: C3S URDB describes timeliness as “the ability of the
publish/subscribe middleware to provide the expected service within
known time bounds”

{empty}[SOURCE: Adapted from ESA S3 User Guide]

[#_Toc161309013 .anchor]##[.underline]#Vertical# [.underline]#levels#

Levels of a vertical discretization. Examples may be pressure levels in
an atmospheric model reanalysis or height levels in a forest biomass EO
product.

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|1,5,10 meter; 1000, 850, 500 hPa |meter, hPa, unitless
|===

{empty}[SOURCE: KCEO]

== EO-derived/Application attributes

=== Baseline

It is the reference period, time or measure against which the
information is assessed or compared. For example, in climate change
projections a baseline may be any 30-year period of observations
(1961-1990, etc.) used as reference to calculate the future change; In
monitoring wetlands degradation one of the indicators of wetlands
condition is wetland connectivity, so that setting the baseline year to
compute the baseline indicator of wetlands connectivity can be used to
report the indicator change for all the other years.

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|2000; 1990-2020 |year
|===

{empty}[SOURCE: KCEO]

=== Classification system

The nomenclature used to classify the information in categorical
thematic classes (ex: EUNIS, MAES ecosystems, Corine Land Cover, LCCS).

{empty}[SOURCE: KCEO]

=== Classification system levels

The levels in a hierarchical classification system. For example, Corine
Land Cover is made up of three nested levels that classify land cover
with increasing details:

_2 Agricultural Areas_

_2.1 Arable lands_

____
_2.1.1 Non-irrigated arable land_

_2.1.2 Permanently irrigated land_

_2.1.3 Rice fields_
____

{empty}[SOURCE: KCEO]

[#_Toc161309018 .anchor]####Climate projection

A climate projection is the simulated response of the climate system to
a scenario of future emission or concentration of greenhouse gases
(GHGs) and aerosols, generally derived using climate models. Climate
projections are distinguished from climate predictions by their
dependence on the emission/concentration/radiative forcing scenario
used, which is in turn based on assumptions concerning, for example,
future socioeconomic and technological developments that may or may not
be realized.

{empty}[SOURCE: IPCC]

=== Forecast range

The forecasted period

{empty}[SOURCE: KCEO]

=== Forecast lead time

The length of time between the issuance of a forecast and the occurrence
of the phenomena that were predicted. It is expressed in time intervals
in a forecasted period, for example 6-hour intervals for a medium-range
forecast.

[width="100%",cols="50%,50%",options="header",]
|===
|Entry format example |Valid unit
|6 h, 1 d |Year, month, day, hour
|===

NOTE 1: UNTERM, International Glossary of Hydrology, WMO/UNESCO, 2011
describes forecast lead time as “interval of time between the issuing of
a forecast (warning) and the expected occurrence of the forecast event”

{empty}[SOURCE: KCEO]

=== [.underline]#Thematic resolution#

The level of categorical detail of information expressed by the number
of classes

{empty}[SOURCE: CGLS]

=== Thematic uncertainty

Uncertainty associated with the method of classification.

NOTE 1: Typically, it is computed from the error matrix.

NOTE 2: For a review of classification uncertainty metrics consult Ye et
al. 2018.

{empty}[SOURCE: KCEO]

== Climate Adaptation

=== Outcome & Impact

Outcome is regarded short-term, while impact is regarded long-term
according to X. However, in the Horizon Europe Missions terminology,
impact is regarded short-term.

== Other

=== Data access

The service to disseminate data

{empty}[SOURCE: KCEO]

=== 

=== Data format

Structured data that is machine readable and can be automatically read
and processed by a computer, such as HDF, NetCDF, CSV, JSON, XML, etc.

{empty}[SOURCE: CEOS Wiki]

=== Data licencing

A legal instrument by which a copyright holder may grant rights over the
protected work. Data and content is open if it is subject to an
explicitly-applied licence that conforms to the Open Definition. A range
of standard open licenses are available, such as the Creative Commons
CC-BY licence, which requires only attribution.

{empty}[SOURCE: CEOS Wiki]

=== Dwell time

The time that an antenna beam spends on a target.

NOTE 1: in the context of radar sensing

=== Policy

A deliberate system of guidelines to guide decisions and achieve
rational outcomes. A policy is a statement of intent and is implemented
as a procedure or protocol. Policies are typically promulgated through
official written documents.

{empty}[SOURCE: Wikipedia]

=== Policy file(s)

One or more policy documents that represent the official written
reference for a given Policy.

{empty}[SOURCE: KCEO]

=== Policy cycle

A well-established concept, which is typically taught as the rational
model of policy decision-making. It is an idealised view of the policy
process

{empty}[SOURCE:
https://digital-strategy.ec.europa.eu/en/library/quality-public-administration-toolbox-practitioners]

=== Policy making

The process by which governments translate their political vision into
programmes and actions to deliver 'outcomes' - desired change in the
real world.

{empty}[SOURCE:
https://digital-strategy.ec.europa.eu/en/library/quality-public-administration-toolbox-practitioners]

=== Policy milestone

Policy milestones mark significant progress in addressing specific
issues, or crucial decision points where significant choices are made.
Concrete examples of policy milestones are: policy planning and
proposing, impact assessment, implementation, or implementation cycles
(e.g., Water Framework Directive, Marine Strategy Framework Directive),
achievement of policy objectives and policy targets, evaluating and
improvement of existing laws.

=== [Source: KCEO]

=== 

=== Policy objective

Desired outcome that policymakers wish to achieve

=== Policy target

Specific level or rate set for the policy objective

=== Update frequency

The frequency at which the product is available to users.

NOTE 1: also known in product catalogues as dissemination frequency

{empty}[SOURCE: KCEO]

=== User Interface

Set of all the components of an interactive system that provide
information and controls for the user to accomplish specific tasks with
the interactive system

{empty}[SOURCE:ISO 9241-110:2020, 3.10]

== Resources/Glossaries

IPCC https://www.ipcc.ch/sr15/chapter/glossary/

UNTERM https://unterm.un.org/unterm2/en/

GEOLEXICA OSGEO https://osgeo.geolexica.org/

W3C:https://w3c.github.io/sdw/bp

INSPIRE-WCS: https://inspire-wcs.eu

GCOS-154: https://library.wmo.int/doc_num.php?explnum_id=3710

GEOGlos: gEOGlos

CEOS-ARD: https://ceos.org/ard/

CEOS Wiki: https://calvalportal.ceos.org/t-d_wiki

EFSG: https://www.efgs.info/information-base/introduction/terminology/

ESC:
http://undocs.org/ece/trans/sc.1/ge.21/2018/1[ECE/TRANS/SC.1/GE.21/2018/1]

ESA:
https://earth.esa.int/eogateway/documents/20142/37627/Mission-Quality-Assessment-Guidelines-v2.2.pdf/033c703e-02f8-d993-9859-560aeb61d2a0?version=1.0&t=1676561363850

WMO-WIGOS https://library.wmo.int/doc_num.php?explnum_id=10109

ESA S3 User Guide
https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-3-altimetry/product-types/nrt-or-ntc

BIPM https://www.bipm.org/en/

JCGM GUM
https://www.bipm.org/documents/20126/50065290/JCGM_GUM_6_2020.pdf/d4e77d99-3870-0908-ff37-c1b6a230a337

BIPM VIM https://jcgm.bipm.org/vim/en/

CGLS Copernicus Global Land Service

FIDUCEO https://research.reading.ac.uk/fiduceo/glossary/

ISO 8601-1:2019 Date and time - Representations for information
interchange - Part 1: Basic rules

ISO 191790-1:2021 Geographic information – Discrete Global Grid Systems
Specifications – Part 1: Core Reference System and Operations, and Equal
Area Earth Reference SYstem

Temporal elements referenced in WIGOS metadata

== References

Ye, S., Pontius, R. G., & Rakshit, R. (2018). A review of accuracy
assessment for object-based image analysis: From per-pixel to
per-polygon approaches. In ISPRS Journal of Photogrammetry and Remote
Sensing (Vol. 141, pp. 137–147). Elsevier B.V.
https://doi.org/10.1016/j.isprsjprs.2018.04.002
